### ISSUE TITLE
eventorganiser-admin-style.css "hide post date filter" not specific enough

### ISSUE THREAD

**Issue by Pixelatic** [stephenharris/Event-Organiser#176]
The "hide post date filter" rule in eventorganiser-admin-style.css currently hides the post date filter for ALL post types in the dashboard, not just events.

Adding the "cp-event" class as the parent selector for the rule hides the post date filter for event post types while showing this as normal for others.

``` css
/*Hide post date filter*/
.cp-event .tablenav.top .alignleft.actions select[name="m"] {
  display: none;
 }
```
